database:
  use-in-memory: true
  postgres:
    host: localhost
    port: 15400
    user: imageer_user
    password: 1m4g33r_u53r_p455
    database: imageer

crypt:
  aes:
    key: some-very-strong-and-long-aes-key
