log:
  format: text # pretty, text, json
  level: debug # debug, info, warn, error
  add-source: true

web:
  show-banner: true
  show-openapi-docs: true
  cors:
    allow-origins: http://localhost:5173
    allow-credentials: true
    max-age: 3h

kubernetes:
  enabled: false

database:
  use-in-memory: true
  postgres:
    host: localhost
    port: 15400
    user: imageer_user
    password: 1m4g33r_u53r_p455
    database: imageer

crypt:
  aes:
    key: some-very-strong-and-long-aes-key
