kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "imageer-processor.fullname" . }}
  labels:
    {{- include "imageer-processor.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
